export default function Page() {
  return (
    <div className="container">
      <h1>Conditions of Use</h1>
      <br />
      <p>
        Please read these conditions carefully before using the Infi Browser
        Application. By using the Infi Browser Application, you signify your
        agreement to be bound by these conditions.
      </p>
      <br />
      <p>
        In addition, when you use any current or future Infi Browser service
        (eg. Wish List or Marketplace), you will also be subject to the terms,
        guidelines and conditions applicable to that Infi Browser Service.
        ("Terms"). If these Conditions of Use are inconsistent with such Terms,
        the Terms will control.
      </p>
      <br />
      <p>
        These "Conditions of Use" constitute an electronic record within the
        meaning of the applicable law. This electronic record is generated by a
        computer system and does not require any physical or digital signatures.
      </p>{" "}
      <br />
      <p>
        <ul>
          <li>Conditions Relating to Your Use of Infi Browser</li>
          <li>Notice and Procedure for Making Claims of Infringement</li>
          <li>
            Notice and Procedure for Notifying Infi Browser of Objectionable
            Content
          </li>
          <li>Conditions Relating to Your Use of Infi Browser</li>
        </ul>
      </p>
      <br />
      <h1>Conditions Relating to Your Use of Infi Browser</h1> <br /> <br />
      <h3>1.Your Account</h3> <br />
      <br />
      <p style={{ paddingLeft: "7%" }}>
        If you use the Application, you are responsible for maintaining the
        confidentiality of your account and password and for restricting access
        to your Mobile to prevent unauthorised access to your account. You agree
        to accept responsibility for all activities that occur under your
        account or password. You should take all necessary steps to ensure that
        the password is kept confidential and secure and should inform us
        immediately if you have any reason to believe that your password has
        become known to anyone else, or if the password is being, or is likely
        to be, used in an unauthorised manner. Please ensure that the details
        you provide us with are correct and complete and inform us immediately
        of any changes to the information that you provided when registering.
        You can access and update much of the information you provided us with
        in the Your Account.
      </p>
      <br />
      <br />
      <h3>1(A). Subject to credibility of free vouchers</h3> <br />
      <br />
      <p>
        To obtain a voucher, you must consume 1000GB of internet on the Infi
        Browser application. In Infi Browser, you will receive a WiFi Id, which
        you and your family members can use on their Infi Browser application.
        The consumption of internet on Infi Browser will be calculated on a
        given WiFi Id. After consuming 1000GB of internet, you will receive a
        free voucher to recharge your WiFi.
      </p>
      <br />
      <br />
      <h3>2.Privacy</h3>
      <br />
      <br />
      <p>
        Please review our Privacy Notice, which also governs your visit to Infi
        Browser, to understand our practices. The personal information / data
        provided to us by you during usage of Infi Browser will be treated as
        strictly confidential and in accordance with the Privacy Notice and
        applicable laws and regulations. If you object to your information being
        transferred or used, please do not use the Application.
      </p>{" "}
      <br />
      <br />
      <h3>3. E-Platform for Communication</h3> <br />
      <br />
      <p>
        You agree, understand and acknowledge that the Application is an online
        platform that enables you to use your mobile phone application on the
        Infi Browser at the seamless connectivity at any time from any location.
        You further agree and acknowledge that Infi Browser is only a
        facilitator and is not and cannot be a party to or control in any manner
        any transactions on the Application.
      </p>
      <br />
      <br />
      <h3>4.Access to Infi Browser</h3>
      <br />
      <br />
      <p>
        We will do our utmost to ensure that availability of the Application
        will be uninterrupted and that transmissions will be error-free.
        However, due to the nature of the Internet, this cannot be guaranteed.
        Also, your access to the Application may also be occasionally suspended
        or restricted to allow for repairs, maintenance, or the introduction of
        new facilities or services at any time without prior notice. We will
        attempt to limit the frequency and duration of any such suspension or
        restriction
      </p>
      <br />
      <br />
      <h3>5.Licence for website access</h3>
      <br />
      <br />
      <p>
        Subject to your compliance with these Conditions of Use and payment of
        applicable fees, if any, Application Services Private Limited grants you
        a limited licence to access and make personal use of this application,
        but not to download (other than page caching) or modify it, or any
        portion of it, except with express written consent of Application
        Services Private Limited and / or its affiliates, as may be applicable.
        This licence does not include any resale or commercial use of this
        application or its contents; any collection and use of any product
        listings, descriptions, or prices; any derivative use of this
        application or its contents; any downloading or copying of account
        information for the benefit of another seller; or any use of data
        mining, robots, or similar data gathering and extraction tools.
        <br />
        <br />
        <br />
        This application or any portion of this application (including but not
        limited to any copyrighted material, trademarks, or other proprietary
        information) may not be reproduced, duplicated, copied, sold, resold,
        visited, distributed or otherwise exploited for any commercial purpose
        without express written consent of Infi Browser Services Private Limited
        and / or its affiliates, as may be applicable.
        <br />
        <br />
        <br />
        You may not frame or use framing techniques to enclose any trademark,
        logo, or other proprietary information (including images, text, page
        layout, or form) of Infi Browser and its affiliates without express
        written consent. You may not use any meta tags or any other "hidden
        text" utilising Infi Browser Services Private Limited's or its
        affiliates' names or trademarks without the express written consent of
        Infi Browser Services Private Limited and / or its affiliates, as
        applicable. Any unauthorised use terminates the permission or license
        granted by Infi Browser Services Private Limited and / or its
        affiliates, as applicable <br />
        <br />
        <br />
        You are granted a limited, revocable, and non-exclusive right to create
        a hyperlink to the Welcome page of Infi Browser as long as the link does
        not portray Infi Browser Services Private Limited, Infi Browser, their
        affiliates, or their products or services in a false, misleading,
        derogatory, or otherwise offensive matter. You may not use any infi
        Browser logo or other proprietary graphic or trademark as part of the
        link without express written consent of Infi Browser Services Private
        Limited and / or its affiliates, as may be applicable.
      </p>{" "}
      <br />
      <br />
      <h3>6. Your Conduct</h3>
      <br />
      <br />
      <p>
        You must not use the application in any way that causes, or is likely to
        cause, the application or access to it to be interrupted, damaged or
        impaired in any way You understand that you, and not Infi Browser, are
        responsible for all electronic communications and content sent from your
        computer to us and you must use the application for lawful purposes
        only. You must not use the application for any of the following: <br />
        <br />
        <ul>
          <li>
            for fraudulent purposes, or in connection with a criminal offense or
            other unlawful activity
          </li>
          <li>
            to send, use or reuse any material that does not belong to you; or
            is illegal, is offensive (including but not limited to material that
            is sexually explicit content or which promotes racism, bigotry,
            hatred or physical harm), deceptive, misleading, abusive, indecent,
            invasive of another's privacy, including bodily privacy, insulting
            or harassing on the basis of gender, blasphemous, defamatory,
            libelous, obscene, pornographic, pedophilic, or menacing; racially
            or ethnically objectionable, or disparaging; in breach of copyright,
            trademark, patent, confidentiality, privacy or any other proprietary
            information or right; or is otherwise injurious to third parties or
            relates to or promotes money laundering or gambling or promotes
            enmity between different groups on the grounds of religion or caste
            with the intent to incite violence; or is harmful to minors in any
            way; or impersonates another person; or threatens the unity,
            integrity, defence, security or sovereignty of India or friendly
            relations with foreign States or public order or causes incitement
            to the commission of any cognisable offence or prevents
            investigation of any offence or is insulting other nation; or
            objectionable or otherwise unlawful in any manner whatsoever; or
            which consists of or contains software viruses or any other computer
            code, file or program designed to interrupt, destroy or limit the
            functionality of any computer resource, political campaigning,
            commercial solicitation, chain letters, mass mailings or any spam;.
          </li>
          <li>
            to deceive or mislead the addressee about the origin of messages.
          </li>
        </ul>
      </p>{" "}
      <br />
      <br />
      <h3>7.Copyright, authors' rights and database rights</h3> <br />
      <br />
      <p>
        All content included on the application, such as text, graphics, logos,
        button icons, images, audio clips, digital downloads, data compilations,
        and software, is the property of Infi Browser Services Private Limited,
        its affiliates or its content suppliers and is protected by India and
        international copyright, authors' rights and database right laws. The
        compilation of all content on this website is the exclusive property of
        Infi Browser Services Private Limited and its affiliates and is
        protected by laws of India and international copyright and database
        right laws. All software used on this application is the property of
        Infi Browser Services Private Limited, its affiliates or its software
        suppliers and is protected by India and international copyright and
        author' rights laws. <br />
        <br />
        You may not systematically extract/ or re-utilise parts of the contents
        of the application without Infi Browser Services Private Limited and /
        or its affiliate's (as may be applicable) express written consent. In
        particular, you may not utilise any data mining, robots, or similar data
        gathering and extraction tools to extract (whether once or many times)
        for re-utilisation of any substantial parts of this application, without
        Infi Browser Services Private Limited and / or its affiliate's (as may
        be applicable) express written consent. You may also not create and/ or
        publish your own database that features substantial (eg: prices and
        product listings) parts of this application without Infi Browser
        Services Private Limited and / or its affiliate's (as may be applicable)
        express written consent.
      </p>
      <br />
      <br />
      <h3>8.Intellectual Property Claims</h3> <br />
      <br />
      <p>
        Infi Browser Services Private Limited and its affiliates respect the
        intellectual property of others. If you believe that your intellectual
        property rights have been used in a way that gives rise to concerns of
        infringement, please follow our Notice and Procedure for Making Claims
        of Right Infringements.
      </p>
      <br />
      <br />
      <h3>9.Trademarks</h3>
      <br />
      <br />
      <p>
        INFI BROWSER, INFI, THE INFI LOGO, AND YOU'RE DONE, , PAYPAGE and other
        marks indicated on our application are trademarks or registered
        trademarks of Infi Browser, Inc. or its subsidiaries (collectively "
        Infi Browser"), in the Indian and/or other jurisdictions. Infi Browser's
        graphics, logos, page headers, button icons, scripts and service names
        are the trademarks or trade dress of Infi Browser. Infi Browser's
        trademarks and trade dress may not be used in connection with any
        product or service that is not Infi Browser's, in any manner that is
        likely to cause confusion among customers, or in any manner that
        disparages or discredits Infi Browser. All other trademarks not owned by
        Infi Browser that appear on this application are the property of their
        respective owners, who may or may not be affiliated with, connected to,
        or sponsored by Infi Browser.
      </p>{" "}
      <br />
      <br />
      <h3>10.Disclaimer</h3> <br />
      <br />
      <p>
        You acknowledge and undertake that you are accessing the services on the
        application and transacting at your own risk and are using your best and
        prudent judgment before entering into any transactions through the
        application.
      </p>{" "}
      <br />
      <br />
      <h3>11.Indemnity and Release</h3> <br />
      <br />
      <p>
        You shall indemnify and hold harmless Infi Browser Services Private
        Limited, its subsidiaries, affiliates and their respective officers,
        directors, agents and employees, from any claim or demand, or actions
        including reasonable attorney's fees, made by any third party or penalty
        imposed due to or arising out of your breach of these Conditions of Use
        or any document incorporated by reference, or your violation of any law,
        rules, regulations or the rights of a third party. <br />
        <br />
        You hereby expressly release Infi Browser Services Private Limited
        and/or its affiliates and/or any of its officers and representatives
        from any cost, damage, liability or other consequence of any of the
        actions/inactions of the vendors and specifically waiver any claims or
        demands that you may have in this behalf under any statute, contract or
        otherwise
      </p>{" "}
      <br />
      <br />
      <h3>12.Communications</h3> <br />
      <br />
      <p>
        When you visit Infi Browser, you are communicating with us
        electronically. You will be required to provide a valid phone number
        while registering yourself in Infi Browser. We may communicate with you
        by e-mail, SMS, phone call or by posting notices on the application or
        by any other mode of communication. For contractual purposes, you
        consent to receive communications (including transactional, promotional
        and/or commercial messages), from us with respect to your use of the
        application.
      </p>
      <br />
      <br />
      <h3>13.Alteration of Service or Amendments to the Conditions</h3> <br />
      <br />
      <p>
        We reserve the right to make changes to our application, policies, and
        these Conditions of Use at any time. You will be subject to the policies
        and Conditions of Use in force at the time that you use the application,
        unless any change to those policies or these conditions is required to
        be made by law or government authority. If any of these conditions is
        deemed invalid, void, or for any reason unenforceable, that condition
        will be deemed severable and will not affect the validity and
        enforceability of any remaining condition.
      </p>
      <br />
      <br />
      <h3>14.Waiver</h3>
      <br />
      <br />
      <p>
        If you breach these conditions and we take no action, we will still be
        entitled to use our rights and remedies in any other situation where you
        breach these conditions.
      </p>{" "}
      <br />
      <br />
      <h3>15.Governing law and Jurisdiction</h3> <br />
      <br />
      <p>
        These conditions are governed by and construed in accordance with the
        laws of India. You agree, as we do, to submit to the exclusive
        jurisdiction of the courts at Delhi.
      </p>
      <br />
      <br />
      <h3>16.Our Details</h3>
      <br />
      <br />
      <p>
        This application is operated by Infi Browser Services Private Limited.{" "}
        <br />
        <br />
        <br />
        For the Infi Browser application, you could contact us by visiting:
        www.infi.in/gp/help/contact-us
      </p>
      <br />
      <br />
      <h3>17.Customer Complaint Details</h3>
      <br />
      <br />
      <p>
        The details pertaining to each customer complaint lodged (including the
        status of the complaint and tracking details) are provided in the return
        e-mails which are sent back to the customers.
      </p>
      <br />
      <br />
      <h3>18.Infi Browser Software Terms</h3>
      <br />
      <br />
      <p>
        In addition to these Conditions of Use, the terms found here apply to
        any software (including any updates or upgrades to the software and any
        related documentation) that we make available to you from time to time
        for your use in connection with Infi Browser Services (the "Infi
        Software").
      </p>
      <br />
      <br />
      <h3>19.Sanctions and Export Policy</h3> <br />
      <br />
      <p>
        You may not use any Infi Browser Service if you are the subject of India
        sanctions or of sanctions consistent with Indian laws imposed by the
        governments of the country where you are using Infi Browser Services.
        You must comply with all India or other export and re-export
        restrictions that may apply to goods, software (including Infi
        Software), technology and services.
      </p>
      <br />
      <br />
      <h1>
        Notice and Procedure for Making Claims of Right Infringements
      </h1>{" "}
      <br />
      <p>
        If you believe that your rights are being infringed, you may fill out
        and submit the Notice Form. We respond expeditiously to rights owners
        and their agents who complete and submit the Notice Form to communicate
        concerns about any alleged infringement. <br />
        <br />
        <br />
        Upon receipt of a Notice Form we may take certain actions, including
        removing information or an item, all of which are taken without any
        admission as to liability and without prejudice to any rights, remedies
        or defenses, all of which are expressly reserved. Furthermore, in
        submitting a Notice Form, you grant to Infi Browser the right to use,
        reproduce, modify, adapt, publish, translate, create derivative works
        from, and display its content throughout the world in any media. This
        includes forwarding the Notice Form to the parties involved in the
        provision of the allegedly infringing content. You agree to indemnify
        Infi Browser for all claims brought by a third party against Infi
        Browser arising out of or in connection with the submission of a Notice
        Form. <br />
        <br />
        Important Warning: giving false, misleading or inaccurate information in
        the Notice Form to Infi Browser may result in civil and/or criminal
        liability. You should contact a legal advisor should you have any
        questions.
      </p>{" "}
      <br />
      <br />
      <h3>Notice Form:</h3>
      <br />
      <br />
      <p>
        If you believe that your rights are being violated by an item or
        information on the Infi Browser site, you may fill out and submit the
        Notice Form (below). This signed form can be sent via E-mail PDF or Fax
        to the Grievance Officer: Important Warning: Giving false, misleading or
        inaccurate information in the Notice to Infi Browser may result in civil
        and/ or criminal liability.
      </p>{" "}
      <br />
      <br />
      <h1>Infi Browser Software Terms</h1>
      <br />
      <br />
      <h3>1.Use of the Infi Browser Software</h3>
      <br />
      <p>
        You may use Infi Browser Software solely for purposes of enabling you to
        use and enjoy the Infi Browser Services as provided by Infi Browser, and
        as permitted by the Conditions of Use, these Infi Browser Software Terms
        and any Terms. You may not incorporate any portion of the Infi Browser
        Software into your own programs or compile any portion of it in
        combination with your own programs, transfer it for use with another
        service, or sell, rent, lease, lend, loan, distribute or sublicense the
        Infi Browser Software or otherwise assign any rights to the Infi Browser
        Software in whole or in part. You may not use the Infi Browser Software
        for any illegal purpose. We may cease providing any Infi Browser
        Software and we may terminate your right to use any Infi Browser
        Software at any time. Your rights to use the Infi Browser Software will
        automatically terminate without notice from us if you fail to comply
        with any of these Infi Browser Software Terms, the Conditions of Use or
        any other Terms. Additional third party terms contained within or
        distributed with certain Infi Browser Software that are specifically
        identified in related documentation may apply to that Infi Browser
        Software (or software incorporated with the Infi Browser Software) and
        will govern the use of such software in the event of a conflict with
        these Conditions of Use. All software used in any Infi Browser Service
        is the property of Infi Browser and/or its affiliates or its software
        suppliers and protected by laws of India including but not limited to
        any other applicable copyright laws.
      </p>
      <br />
      <br />
      <h3>2.Use of Third Party Services</h3> <br />
      <p>
        When you use the Infi Browser Software, you may also be using the
        services of one or more third parties, such as a wireless carrier or a
        mobile platform provider. Your use of these third party services may be
        subject to the separate policies, terms of use, and fees of these third
        parties.
      </p>
      <br />
      <br />
      <h3>3.No Reverse Engineering</h3>
      <br />
      <p>
        You may not, and you will not encourage, assist or authorize any other
        person to copy, modify, reverse engineer, decompile or disassemble, or
        otherwise tamper with, the Infi Browser Software, whether in whole or in
        part, or create any derivative works from or of the Infi Browser
        Software.
      </p>
      <br />
      <br />
      <h3>Updates</h3>
      <br />
      <br />
      <p>
        In order to keep the Infi Browser Software up-to-date, we may offer
        automatic or manual updates at any time and without notice to you.
      </p>
    </div>
  );
}
